"""empty message

Revision ID: 5481328f828d
Revises:
Create Date: 2026-01-13 20:15:15.996639

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5481328f828d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chave_compra",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("id_message", sa.UUID(), nullable=True),
        sa.Column("id_uasg_identificacao", sa.Integer(), nullable=True),
        sa.Column("id_modalidade", sa.Integer(), nullable=True),
        sa.Column("numero", sa.Integer(), nullable=True),
        sa.Column("ano", sa.Integer(), nullable=True),
        sa.Column("numero_uasg", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "key_words",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("numero_compra", sa.String(), nullable=False),
        sa.Column("palavra", sa.String(), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_key_words_numero_compra"), "key_words", ["numero_compra"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tipo_remetente", sa.String(), nullable=True),
        sa.Column("identificador_item", sa.Integer(), nullable=True),
        sa.Column("texto", sa.Text(), nullable=True),
        sa.Column("categoria", sa.String(), nullable=True),
        sa.Column("data_hora", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("cnpj_rementente", sa.String(), nullable=True),
        sa.Column("cnpj_destinatario", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages")
    op.drop_index(op.f("ix_key_words_numero_compra"), table_name="key_words")
    op.drop_table("key_words")
    op.drop_table("chave_compra")
    # ### end Alembic commands ###
