"""empty message

Revision ID: d9835f7f5b3f
Revises: 
Create Date: 2026-01-12 10:45:30.287923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9835f7f5b3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chave_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_message', sa.UUID(), nullable=True),
    sa.Column('id_uasg_identificacao', sa.Integer(), nullable=True),
    sa.Column('id_modalidade', sa.Integer(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('numero_uasg', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tipo_remetente', sa.String(), nullable=True),
    sa.Column('identificador_item', sa.Integer(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.Column('cnpj_rementente', sa.String(), nullable=True),
    sa.Column('cnpj_destinatario', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('chave_compra')
    # ### end Alembic commands ###
